modLoader="javafml" #mandatory
loaderVersion="[27,)" #mandatory

[[mods]] #mandatory
	modId="woolplates" #mandatory
	version="v1.2.1" #mandatory
	displayName="Wool Pressure Plates" #mandatory
	description='''Adds pressure plates made out of wool.''' #mandatory
	issueTrackerURL="https://github.com/bl4ckscor3/WoolPlates/issues"
	displayURL="http://minecraft.curseforge.com/projects/wool-pressure-plates"
	authors="bl4ckscor3"

[[dependencies.woolplates]]
    modId="forge"
    mandatory=true
    versionRange="[27,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.woolplates]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14,1.15)"
    ordering="NONE"
    side="BOTH"