modLoader="javafml"
loaderVersion="[38,)"
license="GNU GPL v3.0 https://github.com/bl4ckscor3/WoolPlates/blob/1.18/LICENSE"
issueTrackerURL="https://github.com/bl4ckscor3/WoolPlates/issues"

[[mods]]
	modId="woolplates"
	version="${file.jarVersion}"
	displayName="Wool Pressure Plates"
	description='''Adds pressure plates made out of wool.'''
	displayURL="https://www.curseforge.com/minecraft/mc-mods/wool-pressure-plates"
	authors="bl4ckscor3"

[[dependencies.woolplates]]
    modId="forge"
    mandatory=true
    versionRange="[38,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.woolplates]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18,1.19)"
    ordering="NONE"
    side="BOTH"